/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_edd;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author OscarPC
 */
public class Ingreso_Plantas extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    static String cadenaplantas = "";
    
    public Ingreso_Plantas() {
        initComponents();
        
        
    }
    
    public static void TextoPlantas() throws FileNotFoundException
    {
        
        Lista_Plantas auxiliar = null;
        Objeto_Planta nuevo = null;
        nuevo = auxiliar.cabeza; 
        //JOptionPane.showMessageDialog(null, "Nombre: " + nuevo.nombre);
        while(nuevo != null)
        {
        if(nuevo.sig != null)
        {    
        cadenaplantas = cadenaplantas + nuevo.nombre + "->";
        //JOptionPane.showMessageDialog(null, cadenaplantas);
        nuevo = nuevo.sig;
        }
        else
        {
            cadenaplantas = cadenaplantas + nuevo.nombre + ";";  
            //JOptionPane.showMessageDialog(null, cadenaplantas);
            nuevo = nuevo.sig;
        }
        }
     
        //JOptionPane.showMessageDialog(null, "Termino bien la cadena de plantas");
    }
      
    
    

    public void LlenarImagen(String path)
    {
    ImageIcon fot = new ImageIcon(path);
    Icon icono = new ImageIcon(fot.getImage().getScaledInstance(Label_Imagen.getWidth(), Label_Imagen.getHeight(), java.awt.Image.SCALE_DEFAULT));
    Label_Imagen.setIcon(icono);
    Label_Imagen.repaint();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Label_Imagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        Txt_At = new javax.swing.JTextField();
        Txt_Def = new javax.swing.JTextField();
        Combo_Tipo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 763, 342));
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Ingreso de Plantas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(80, 11, 614, 56);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        Label_Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Label_Imagen);
        Label_Imagen.setBounds(23, 23, 125, 116);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jButton1.setText("Seleccionar Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(23, 157, 130, 20);

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(243, 26, 100, 14);

        jLabel3.setText("Ataque:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(243, 64, 100, 14);

        jLabel4.setText("Defensa:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(243, 102, 100, 14);

        jLabel5.setText("Tipo:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(243, 140, 100, 14);
        jPanel2.add(Txt_Nombre);
        Txt_Nombre.setBounds(350, 20, 172, 20);
        jPanel2.add(Txt_At);
        Txt_At.setBounds(350, 60, 172, 20);
        jPanel2.add(Txt_Def);
        Txt_Def.setBounds(350, 100, 172, 20);

        Combo_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ataque Directo", "Disparo" }));
        Combo_Tipo.setSelectedItem("Ataque Directo"
            + "Disparo");
        jPanel2.add(Combo_Tipo);
        Combo_Tipo.setBounds(350, 140, 170, 20);

        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(250, 200, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 80, 610, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        String path = "";
        String nombre;
        int ataque;
        int defensa;
        String tipo;
        JFileChooser selec = new JFileChooser();
        int dec = selec.showOpenDialog(null);
        if (dec == JFileChooser.APPROVE_OPTION) {
        File file = selec.getSelectedFile();
        path = file.getPath();
        } 
        else 
        {
        JOptionPane.showMessageDialog(null, "Proceso cancelado!");
        }
        
        LlenarImagen(path);
        nombre = Txt_Nombre.getText();
        ataque = Integer.parseInt(Txt_At.getText());
        defensa = Integer.parseInt(Txt_Def.getText());
        tipo = (String)Combo_Tipo.getSelectedItem();
        
        Lista_Plantas nuevo = new Lista_Plantas();
        nuevo.InsertarPlanta(path, nombre, defensa, ataque, tipo);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_Tipo;
    private javax.swing.JLabel Label_Imagen;
    private javax.swing.JTextField Txt_At;
    private javax.swing.JTextField Txt_Def;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
